import type { DigitalDocumentItem } from "../types/document.types";

export const initialDocuments: DigitalDocumentItem[] = [
  {
    id: "doc-1",
    title: "SOLAS Safety Construction - KM Solid Horizon",
    category: "Sertifikat Kapal",
    vesselName: "KM Solid Horizon",
    clientCompany: "PT Nusantara Cargo Line",
    fileType: "PDF",
    fileSize: "2.4 MB",
    version: "v1.1",
    status: "Menunggu Approval",
    expiryDate: "2027-08-10",
    uploadedBy: "Budi Santoso (Staff)",
    uploadedAt: "2026-08-09 10:15",
    auditTrail: [
      {
        id: "at-1",
        action: "Document Uploaded",
        actor: "Budi Santoso (Staff)",
        timestamp: "2026-08-09 10:15",
        note: "Mengunggah hasil perpanjangan fisik dari BKI.",
      },
    ],
    versions: [
      {
        version: "v1.1",
        uploadedBy: "Budi Santoso (Staff)",
        uploadedAt: "2026-08-09 10:15",
        fileSize: "2.4 MB",
      },
      {
        version: "v1.0",
        uploadedBy: "Budi Santoso (Staff)",
        uploadedAt: "2023-08-01 09:00",
        fileSize: "2.1 MB",
      },
    ],
  },
  {
    id: "doc-2",
    title: "IOPP Oil Pollution Prevention - KM Samarinda Titan",
    category: "Sertifikat Kapal",
    vesselName: "KM Samarinda Titan",
    clientCompany: "PT Samarinda Trans Energi",
    fileType: "PDF",
    fileSize: "3.1 MB",
    version: "v1.0",
    status: "Final",
    expiryDate: "2027-08-25",
    uploadedBy: "Siti Rahma (Staff)",
    uploadedAt: "2026-08-05 14:00",
    approvedBy: "Hendra Wijaya (Supervisor)",
    approvedAt: "2026-08-05 16:30",
    auditTrail: [
      {
        id: "at-2",
        action: "Document Approved to Final",
        actor: "Hendra Wijaya (Supervisor)",
        timestamp: "2026-08-05 16:30",
        note: "Disetujui. Tanggal masa berlaku sertifikat kapal diperbarui.",
      },
    ],
    versions: [
      {
        version: "v1.0",
        uploadedBy: "Siti Rahma (Staff)",
        uploadedAt: "2026-08-05 14:00",
        fileSize: "3.1 MB",
      },
    ],
  },
  {
    id: "doc-3",
    title: "Surat Kontrak Keagenan PT Samarinda Trans Energi",
    category: "Dokumen Klien",
    clientCompany: "PT Samarinda Trans Energi",
    fileType: "PDF",
    fileSize: "5.8 MB",
    version: "v1.0",
    status: "Final",
    uploadedBy: "Siti Rahma (Sales)",
    uploadedAt: "2026-08-01 11:20",
    approvedBy: "Arafat Nayeem (Super Admin)",
    approvedAt: "2026-08-01 13:00",
    auditTrail: [
      {
        id: "at-3",
        action: "Contract Approved",
        actor: "Arafat Nayeem (Super Admin)",
        timestamp: "2026-08-01 13:00",
      },
    ],
    versions: [],
  },
  {
    id: "doc-4",
    title: "SOP Layanan Keagenan Pelabuhan 2026",
    category: "Dokumen Internal",
    fileType: "PDF",
    fileSize: "1.2 MB",
    version: "v2.0",
    status: "Final",
    uploadedBy: "Arafat Nayeem (Super Admin)",
    uploadedAt: "2026-01-10 08:00",
    auditTrail: [],
    versions: [],
  },
];
