import type { LeadItem, ContactItem, DealItem, InteractionLog } from "../types/crm.types";

export const initialLeads: LeadItem[] = [
  {
    id: "lead-1",
    companyName: "PT Nusantara Cargo Line",
    picName: "Capt. Herman Wijaya",
    picPhone: "0812-9876-5432",
    picEmail: "herman@nusantaracargo.co.id",
    source: "Pameran Maritim 2026",
    vesselCount: 6,
    vesselTypes: ["Cargo", "Bulk Carrier"],
    potentialValue: 450000000,
    priorityScore: 92,
    stage: "Negosiasi",
    isStagnant: false,
    lastActivityDate: "2026-08-08",
    createdAt: "2026-07-15",
    notes: "Membutuhkan layanan keagenan terpadu dan monitoring sertifikat SOLAS.",
  },
  {
    id: "lead-2",
    companyName: "PT Samarinda Trans Energi",
    picName: "Bambang Soetrisno",
    picPhone: "0811-2345-6789",
    picEmail: "bambang@samarindaenergy.com",
    source: "Referal Klien",
    vesselCount: 12,
    vesselTypes: ["Tanker", "Tugboat"],
    potentialValue: 1200000000,
    priorityScore: 98,
    stage: "Menang",
    isStagnant: false,
    lastActivityDate: "2026-08-09",
    createdAt: "2026-06-20",
    notes: "Closing deal keagenan 12 tanker minyak. Siap didaftarkan armadanya.",
  },
  {
    id: "lead-3",
    companyName: "CV Lautan Makmur Transport",
    picName: "Diah Permata",
    picPhone: "0813-5555-8888",
    picEmail: "diah@lautanmakmur.co.id",
    source: "Website Direct Inquiry",
    vesselCount: 3,
    vesselTypes: ["Tugboat"],
    potentialValue: 180000000,
    priorityScore: 65,
    stage: "Presentasi",
    isStagnant: true, // No activity > 14 days
    lastActivityDate: "2026-07-20",
    createdAt: "2026-07-10",
    notes: "Perlu follow up ulang karena stagnan selama 2 minggu.",
  },
  {
    id: "lead-4",
    companyName: "PT Batam Global Maritime",
    picName: "Eko Prasetyo",
    picPhone: "0852-1122-3344",
    picEmail: "eko@batamglobalmaritime.com",
    source: "Cold Call Sales",
    vesselCount: 4,
    vesselTypes: ["Cargo"],
    potentialValue: 250000000,
    priorityScore: 78,
    stage: "Dihubungi",
    isStagnant: false,
    lastActivityDate: "2026-08-07",
    createdAt: "2026-08-01",
    notes: "Sudah dikirimkan profile perusahaan dan brosur layanan.",
  },
  {
    id: "lead-5",
    companyName: "PT Indonesia Oceanic Lines",
    picName: "Rina Kusuma",
    picPhone: "0817-4433-2211",
    picEmail: "rina@oceaniclines.id",
    source: "Email Campaign",
    vesselCount: 2,
    vesselTypes: ["Cargo"],
    potentialValue: 120000000,
    priorityScore: 50,
    stage: "Baru",
    isStagnant: false,
    lastActivityDate: "2026-08-09",
    createdAt: "2026-08-09",
    notes: "Prospek baru masuk hari ini.",
  },
];

export const initialContacts: ContactItem[] = [
  {
    id: "cont-1",
    name: "Capt. Herman Wijaya",
    company: "PT Nusantara Cargo Line",
    position: "Fleet Operations Manager",
    email: "herman@nusantaracargo.co.id",
    phone: "0812-9876-5432",
    isClientActive: false,
    interactionCount: 5,
    lastContacted: "2026-08-08",
  },
  {
    id: "cont-2",
    name: "Bambang Soetrisno",
    company: "PT Samarinda Trans Energi",
    position: "VP Procurement & Logistics",
    email: "bambang@samarindaenergy.com",
    phone: "0811-2345-6789",
    isClientActive: true,
    interactionCount: 12,
    lastContacted: "2026-08-09",
  },
  {
    id: "cont-3",
    name: "Diah Permata",
    company: "CV Lautan Makmur Transport",
    position: "Operational Supervisor",
    email: "diah@lautanmakmur.co.id",
    phone: "0813-5555-8888",
    isClientActive: false,
    interactionCount: 2,
    lastContacted: "2026-07-20",
  },
];

export const initialDeals: DealItem[] = [
  {
    id: "deal-101",
    leadId: "lead-1",
    title: "Penawaran Keagenan Kargo PT Nusantara Cargo",
    companyName: "PT Nusantara Cargo Line",
    vesselCount: 6,
    proposalValue: 450000000,
    status: "Direview",
    sentDate: "2026-08-05",
    validUntil: "2026-08-30",
  },
  {
    id: "deal-102",
    leadId: "lead-2",
    title: "Kontrak Layanan Keagenan Tanker Minyak",
    companyName: "PT Samarinda Trans Energi",
    vesselCount: 12,
    proposalValue: 1200000000,
    status: "Disetujui",
    sentDate: "2026-07-25",
    validUntil: "2026-08-25",
  },
];

export const initialInteractions: InteractionLog[] = [
  {
    id: "int-1",
    contactId: "cont-1",
    type: "Proposal",
    summary: "Mengirimkan draf dokumen penawaran keagenan 6 armada kargo",
    actor: "Siti Rahma (Sales)",
    timestamp: "2026-08-05 14:30",
  },
  {
    id: "int-2",
    contactId: "cont-2",
    type: "Meeting",
    summary: "Penandatanganan Memorandum of Understanding (MoU) Keagenan Tanker",
    actor: "Arafat Nayeem (Super Admin)",
    timestamp: "2026-08-09 10:00",
  },
];
