import {
  LayoutDashboard,
  Users,
  UserCircle,
  Calendar,
  FileText,
  Pill,
  Package,
  ShoppingCart,
  Receipt,
  Database,
  BarChart3,
  Activity,
  Stethoscope,
  ClipboardList,
  Warehouse,
  Truck,
  FolderTree,
  MapPin,
  Building2,
  Ruler,
  Store,
  Utensils,
  Grid,
  Briefcase,
  Heart,
  TrendingUp,
  Contact,
  Bot,
  Sparkles,
  Handshake,
  DollarSign,
  Settings,
  Shield,
  Menu,
  Tag,
  Layers,
  CreditCard,
  Clock,
  Package2,
  Box,
  Map,
  UserCheck,
  Home,
  PieChart,
  Globe,
  UserPlus,
  Calculator,
  Funnel,
  File,
  FileMinus,
  Target,
  BarChart2,
  Book,
  BookOpen,
  ShieldCheck,
  Edit3,
  List,
  ArrowRightLeft,
  TrendingDown,
  ShoppingBag,
  Star,
  Flag,
  Folder,
  Award,
  GraduationCap,
  UserCog,
  Landmark,
  Lock,
  ClipboardCheck,
  FileCheck,
  Wallet,
  Coins,
  CalendarCheck,
  Building,
  Scale,
  Table,
  Percent,
  LayoutList,
  CheckSquare,
  Banknote,
  Hammer,
  Zap,
  Kanban,
  Route,
  RotateCcw,
  Moon,
  MonitorCheck,
  Boxes,
  ScanLine,
  ShoppingBasket,
  MessageSquareHeart,
  MessageCircle,
  ClipboardPen,
  ScrollText,
} from "lucide-react";

const iconMap: Record<string, React.ReactNode> = {
  // Dashboard icons
  dashboard: <LayoutDashboard className="h-4 w-4" />,
  "layout-dashboard": <LayoutDashboard className="h-4 w-4" />,

  // Data Master / Database icons
  database: <Database className="h-4 w-4" />,
  building: <Building className="h-4 w-4" />,
  "building-2": <Building2 className="h-4 w-4" />,
  grid: <Grid className="h-4 w-4" />,
  briefcase: <Briefcase className="h-4 w-4" />,
  user: <UserCircle className="h-4 w-4" />,
  users: <Users className="h-4 w-4" />,
  heart: <Heart className="h-4 w-4" />,
  handshake: <Handshake className="h-4 w-4" />,
  "dollar-sign": <DollarSign className="h-4 w-4" />,
  dollarsign: <DollarSign className="h-4 w-4" />,
  settings: <Settings className="h-4 w-4" />,
  shield: <Shield className="h-4 w-4" />,
  menu: <Menu className="h-4 w-4" />,
  tag: <Tag className="h-4 w-4" />,
  layers: <Layers className="h-4 w-4" />,
  "credit-card": <CreditCard className="h-4 w-4" />,
  creditcard: <CreditCard className="h-4 w-4" />,
  clock: <Clock className="h-4 w-4" />,
  "package-2": <Package2 className="h-4 w-4" />,
  package2: <Package2 className="h-4 w-4" />,
  box: <Box className="h-4 w-4" />,
  map: <Map className="h-4 w-4" />,
  "user-check": <UserCheck className="h-4 w-4" />,
  usercheck: <UserCheck className="h-4 w-4" />,
  home: <Home className="h-4 w-4" />,
  "pie-chart": <PieChart className="h-4 w-4" />,
  piechart: <PieChart className="h-4 w-4" />,
  globe: <Globe className="h-4 w-4" />,
  "user-plus": <UserPlus className="h-4 w-4" />,
  userplus: <UserPlus className="h-4 w-4" />,
  calculator: <Calculator className="h-4 w-4" />,
  funnel: <Funnel className="h-4 w-4" />,
  file: <File className="h-4 w-4" />,
  "file-minus": <FileMinus className="h-4 w-4" />,
  fileminus: <FileMinus className="h-4 w-4" />,
  target: <Target className="h-4 w-4" />,
  "bar-chart-2": <BarChart2 className="h-4 w-4" />,
  barchart2: <BarChart2 className="h-4 w-4" />,
  book: <Book className="h-4 w-4" />,
  "book-open": <BookOpen className="h-4 w-4" />,
  bookopen: <BookOpen className="h-4 w-4" />,
  "shield-check": <ShieldCheck className="h-4 w-4" />,
  shieldcheck: <ShieldCheck className="h-4 w-4" />,
  "edit-3": <Edit3 className="h-4 w-4" />,
  edit3: <Edit3 className="h-4 w-4" />,
  list: <List className="h-4 w-4" />,
  "arrow-right-left": <ArrowRightLeft className="h-4 w-4" />,
  arrowrightleft: <ArrowRightLeft className="h-4 w-4" />,
  "trending-down": <TrendingDown className="h-4 w-4" />,
  trendingdown: <TrendingDown className="h-4 w-4" />,
  "shopping-bag": <ShoppingBag className="h-4 w-4" />,
  shoppingbag: <ShoppingBag className="h-4 w-4" />,
  star: <Star className="h-4 w-4" />,

  // Sales icons
  "trending-up": <TrendingUp className="h-4 w-4" />,
  trendingup: <TrendingUp className="h-4 w-4" />,
  contact: <Contact className="h-4 w-4" />,
  // Returns icon (rotate-ccw)
  "rotate-ccw": <RotateCcw className="h-4 w-4" />,
  rotate_ccw: <RotateCcw className="h-4 w-4" />,
  rotateccw: <RotateCcw className="h-4 w-4" />,
  returns: <RotateCcw className="h-4 w-4" />,
  return: <RotateCcw className="h-4 w-4" />,

  // Calendar & Time icons
  calendar: <Calendar className="h-4 w-4" />,
  "calendar-check": <CalendarCheck className="h-4 w-4" />,
  calendarcheck: <CalendarCheck className="h-4 w-4" />,

  // File & Document icons
  filetext: <FileText className="h-4 w-4" />,
  "file-text": <FileText className="h-4 w-4" />,
  "file-check": <FileCheck className="h-4 w-4" />,
  filecheck: <FileCheck className="h-4 w-4" />,

  // Product & Package icons
  pill: <Pill className="h-4 w-4" />,
  package: <Package className="h-4 w-4" />,

  // Shopping & Commerce icons
  shoppingcart: <ShoppingCart className="h-4 w-4" />,
  "shopping-cart": <ShoppingCart className="h-4 w-4" />,
  receipt: <Receipt className="h-4 w-4" />,

  // Chart & Analytics icons
  barchart3: <BarChart3 className="h-4 w-4" />,
  "bar-chart-3": <BarChart3 className="h-4 w-4" />,
  table: <Table className="h-4 w-4" />,
  scale: <Scale className="h-4 w-4" />,

  // Activity & Health icons
  activity: <Activity className="h-4 w-4" />,
  stethoscope: <Stethoscope className="h-4 w-4" />,

  // Clipboard icons
  clipboardlist: <ClipboardList className="h-4 w-4" />,
  "clipboard-list": <ClipboardList className="h-4 w-4" />,
  "clipboard-check": <ClipboardCheck className="h-4 w-4" />,
  clipboardcheck: <ClipboardCheck className="h-4 w-4" />,

  // Warehouse & Logistics icons
  warehouse: <Warehouse className="h-4 w-4" />,
  "scroll-text": <ScrollText className="h-4 w-4" />,
  scrolltext: <ScrollText className="h-4 w-4" />,
  truck: <Truck className="h-4 w-4" />,

  // Navigation & Location icons
  foldertree: <FolderTree className="h-4 w-4" />,
  "folder-tree": <FolderTree className="h-4 w-4" />,
  mappin: <MapPin className="h-4 w-4" />,
  "map-pin": <MapPin className="h-4 w-4" />,
  ruler: <Ruler className="h-4 w-4" />,
  store: <Store className="h-4 w-4" />,
  utensils: <Utensils className="h-4 w-4" />,
  boxes: <Boxes className="h-4 w-4" />,
  "monitor-check": <MonitorCheck className="h-4 w-4" />,
  monitorcheck: <MonitorCheck className="h-4 w-4" />,
  "scan-line": <ScanLine className="h-4 w-4" />,
  scanline: <ScanLine className="h-4 w-4" />,
  "shopping-basket": <ShoppingBasket className="h-4 w-4" />,
  shoppingbasket: <ShoppingBasket className="h-4 w-4" />,
  flag: <Flag className="h-4 w-4" />,

  // AI & Bot icons
  bot: <Bot className="h-4 w-4" />,
  sparkles: <Sparkles className="h-4 w-4" />,
  "ai-chatbot": <Bot className="h-4 w-4" />,
  "ai-settings": <Sparkles className="h-4 w-4" />,

  // Folder & Organization icons
  folder: <Folder className="h-4 w-4" />,

  // Finance & Money icons
  landmark: <Landmark className="h-4 w-4" />,
  wallet: <Wallet className="h-4 w-4" />,
  coins: <Coins className="h-4 w-4" />,

  // Security icons
  lock: <Lock className="h-4 w-4" />,

  // HRD & Employee icons
  "user-cog": <UserCog className="h-4 w-4" />,
  usercog: <UserCog className="h-4 w-4" />,
  "graduation-cap": <GraduationCap className="h-4 w-4" />,
  graduationcap: <GraduationCap className="h-4 w-4" />,
  award: <Award className="h-4 w-4" />,
  percent: <Percent className="h-4 w-4" />,
  "layout-list": <LayoutList className="h-4 w-4" />,
  "check-square": <CheckSquare className="h-4 w-4" />,
  banknote: <Banknote className="h-4 w-4" />,
  hammer: <Hammer className="h-4 w-4" />,

  // CRM icons
  zap: <Zap className="h-4 w-4" />,
  kanban: <Kanban className="h-4 w-4" />,
  route: <Route className="h-4 w-4" />,

  // Overtime icon (moon for working outside regular hours)
  moon: <Moon className="h-4 w-4" />,

  // Feedback icons
  "message-square-heart": <MessageSquareHeart className="h-4 w-4" />,
  messagesquareheart: <MessageSquareHeart className="h-4 w-4" />,
  "message-circle": <MessageCircle className="h-4 w-4" />,
  messagecircle: <MessageCircle className="h-4 w-4" />,
  "clipboard-pen": <ClipboardPen className="h-4 w-4" />,
  clipboardpen: <ClipboardPen className="h-4 w-4" />,
};

export function getMenuIcon(iconName: string): React.ReactNode {
  return iconMap[iconName.toLowerCase()] || <Database className="h-4 w-4" />;
}
