import { create } from "zustand";
import type {
  Company,
  Contact,
  Vessel,
  Certificate,
  Vendor,
  LeadOpportunity,
  Proposal,
  ServiceRequest,
  OutsourceTask,
  RenewalReminder,
  SalesStage,
  CompanyLifecycleStage,
  ServiceRequestStage,
  OutsourceTaskStage,
  QualificationDiscoveryForm,
} from "@/types/maritime.types";

// Dummy realistic data for Indonesian Shipping Agencies
const initialCompanies: Company[] = [
  {
    id: "comp-1",
    name: "PT Samudera Indonesia Tbk",
    code: "SMC-ID",
    businessType: "Container Carrier",
    operatingArea: "Internasional / Regional SEA",
    fleetCount: 14,
    activeContractsCount: 5,
    lifecycleStage: "Active",
    onboardingDate: "2024-01-15",
    mrrValue: 185000000,
    primaryPicName: "Bambang Prasetyo",
    primaryPicEmail: "bambang.p@samudera.id",
    primaryPicPhone: "+62 811-2345-6789",
    address: "Jl. Kali Besar Barat No. 43, Tambora",
    city: "Jakarta Barat",
    activeCertificatesCount: 52,
    nearExpiryCertificatesCount: 3,
    expiredCertificatesCount: 1,
    notes: "Mitra agen utama rute Tanjung Priok - Tanjung Perak - Singapore.",
  },
  {
    id: "comp-2",
    name: "PT Temas Tbk (Pelayaran Temas)",
    code: "TMS-ID",
    businessType: "Container Carrier",
    operatingArea: "Inter-Island / Antar-Pulau",
    fleetCount: 22,
    activeContractsCount: 8,
    lifecycleStage: "Renewed",
    onboardingDate: "2023-08-10",
    mrrValue: 240000000,
    primaryPicName: "Dewi Lestari",
    primaryPicEmail: "dewi.l@temasline.com",
    primaryPicPhone: "+62 812-9876-5432",
    address: "Jl. Danau Sunter Utara Blok O2",
    city: "Jakarta Utara",
    activeCertificatesCount: 88,
    nearExpiryCertificatesCount: 5,
    expiredCertificatesCount: 0,
    notes: "Kontrak tahunan keagenan kapal feeder peti kemas nusantara.",
  },
  {
    id: "comp-3",
    name: "PT Trans Power Marine Tbk",
    code: "TPM-ID",
    businessType: "Tug & Barge (Coal & Minerals)",
    operatingArea: "Nasional & Domestik",
    fleetCount: 35,
    activeContractsCount: 6,
    lifecycleStage: "Active",
    onboardingDate: "2024-03-01",
    mrrValue: 310000000,
    primaryPicName: "Rudi Hermawan",
    primaryPicEmail: "rudi.h@transpower.co.id",
    primaryPicPhone: "+62 813-1122-3344",
    address: "Kawasan Industri Kendal Kav. 8",
    city: "Kendal, Jawa Tengah",
    activeCertificatesCount: 120,
    nearExpiryCertificatesCount: 8,
    expiredCertificatesCount: 2,
    notes: "Spesialis pengangkutan batubara Kalimantan - Jawa.",
  },
  {
    id: "comp-4",
    name: "PT Wintermar Offshore Marine Tbk",
    code: "WMR-ID",
    businessType: "Offshore Support & Supply",
    operatingArea: "Internasional / Regional SEA",
    fleetCount: 12,
    activeContractsCount: 3,
    lifecycleStage: "Renewal Risk",
    onboardingDate: "2023-11-20",
    mrrValue: 145000000,
    primaryPicName: "Capt. Hendra Wijaya",
    primaryPicEmail: "hendra.w@wintermar.com",
    primaryPicPhone: "+62 811-5566-7788",
    address: "Jl. Kebayoran Lama No. 155",
    city: "Jakarta Selatan",
    activeCertificatesCount: 45,
    nearExpiryCertificatesCount: 4,
    expiredCertificatesCount: 1,
    notes: "Membutuhkan SLA penanganan sertifikasi offshore darurat.",
  },
  {
    id: "comp-5",
    name: "PT Samarinda Trans Energi",
    code: "STE-ID",
    businessType: "Oil & Chemical Tanker",
    operatingArea: "Nasional & Domestik",
    fleetCount: 6,
    activeContractsCount: 2,
    lifecycleStage: "Onboarding",
    onboardingDate: "2026-07-01",
    mrrValue: 95000000,
    primaryPicName: "Siti Rahmawati",
    primaryPicEmail: "siti@ste-maritime.co.id",
    primaryPicPhone: "+62 852-4433-2211",
    address: "Jl. Yos Sudarso No. 88",
    city: "Samarinda",
    activeCertificatesCount: 18,
    nearExpiryCertificatesCount: 2,
    expiredCertificatesCount: 0,
    notes: "Klien baru hasil konversi Sales Pipeline Juli 2026.",
  },
  {
    id: "comp-6",
    name: "PT Buana Lintas Lautan Tbk",
    code: "BULL-ID",
    businessType: "Oil & Chemical Tanker",
    operatingArea: "Global Maritime Route",
    fleetCount: 18,
    activeContractsCount: 4,
    lifecycleStage: "New Client",
    onboardingDate: "2026-08-05",
    mrrValue: 210000000,
    primaryPicName: "Irwan Santoso",
    primaryPicEmail: "irwan.s@bull.co.id",
    primaryPicPhone: "+62 818-0909-8080",
    address: "AXA Tower Lt. 28, Kuningan",
    city: "Jakarta Selatan",
    activeCertificatesCount: 60,
    nearExpiryCertificatesCount: 1,
    expiredCertificatesCount: 0,
    notes: "Tahap serah terima berkas dokumen perizinan kapal tanker.",
  },
  {
    id: "comp-7",
    name: "PT Maritime Express Logistics",
    code: "MEL-ID",
    businessType: "General Cargo & Breakbulk",
    operatingArea: "Nasional & Domestik",
    fleetCount: 5,
    activeContractsCount: 1,
    lifecycleStage: "Dormant",
    onboardingDate: "2023-02-14",
    mrrValue: 45000000,
    primaryPicName: "Agus Supriatna",
    primaryPicEmail: "agus@melogistics.co.id",
    primaryPicPhone: "+62 812-3344-5566",
    address: "Jl. Pelabuhan Tanjung Perak No. 12",
    city: "Surabaya",
    activeCertificatesCount: 15,
    nearExpiryCertificatesCount: 0,
    expiredCertificatesCount: 3,
    notes: "Tidak ada jadwal sandar dalam 90 hari terakhir.",
  },
];

const initialCertificates: Certificate[] = [
  {
    id: "cert-101",
    certificateName: "SOLAS Safety Construction Certificate",
    certificateNumber: "SOL-2024-8891",
    category: "Statutory (SOLAS/MARPOL)",
    vesselId: "vess-1",
    vesselName: "KM Samudera Sejahtera",
    companyId: "comp-1",
    companyName: "PT Samudera Indonesia Tbk",
    issuingAuthority: "Kantor Syahbandar Utama Tanjung Priok",
    issueDate: "2024-08-20",
    expiryDate: "2026-08-25",
    daysRemaining: 15,
    status: "near-expiry",
    lastRenewedBy: "Arafat Nayeem",
  },
  {
    id: "cert-102",
    certificateName: "MARPOL Annex I Oil Pollution Prevention",
    certificateNumber: "MAR-2024-1102",
    category: "Statutory (SOLAS/MARPOL)",
    vesselId: "vess-1",
    vesselName: "KM Samudera Sejahtera",
    companyId: "comp-1",
    companyName: "PT Samudera Indonesia Tbk",
    issuingAuthority: "BKI (Biro Klasifikasi Indonesia)",
    issueDate: "2023-09-10",
    expiryDate: "2026-08-05",
    daysRemaining: -5,
    status: "expired",
    lastRenewedBy: "Bambang P.",
  },
  {
    id: "cert-103",
    certificateName: "Document of Compliance (ISM Code)",
    certificateNumber: "ISM-2025-4421",
    category: "Safety & Security (ISM/ISPS)",
    vesselId: "vess-2",
    vesselName: "KM Temas Express",
    companyId: "comp-2",
    companyName: "PT Temas Tbk (Pelayaran Temas)",
    issuingAuthority: "Direktorat Jenderal Perhubungan Laut",
    issueDate: "2024-01-10",
    expiryDate: "2026-09-15",
    daysRemaining: 36,
    status: "near-expiry",
  },
  {
    id: "cert-104",
    certificateName: "Minimum Safe Manning Certificate",
    certificateNumber: "SMC-2024-0012",
    category: "Crewing & Safe Manning",
    vesselId: "vess-2",
    vesselName: "KM Temas Express",
    companyId: "comp-2",
    companyName: "PT Temas Tbk (Pelayaran Temas)",
    issuingAuthority: "KSOP Kelas I Tanjung Perak",
    issueDate: "2024-03-15",
    expiryDate: "2027-03-15",
    daysRemaining: 217,
    status: "valid",
  },
  {
    id: "cert-105",
    certificateName: "International Load Line Certificate",
    certificateNumber: "ILLC-2023-7721",
    category: "Class & Seaworthiness",
    vesselId: "vess-3",
    vesselName: "TB Trans Power 08 / BG Marine 302",
    companyId: "comp-3",
    companyName: "PT Trans Power Marine Tbk",
    issuingAuthority: "BKI (Biro Klasifikasi Indonesia)",
    issueDate: "2023-11-01",
    expiryDate: "2026-08-30",
    daysRemaining: 20,
    status: "near-expiry",
  },
  {
    id: "cert-106",
    certificateName: "Surat Izin Usaha Perusahaan Angkutan Laut (SIUPAL)",
    certificateNumber: "SIUPAL-DEPHUB-2022-901",
    category: "Legal & SIUPAL",
    vesselId: "vess-4",
    vesselName: "AHTS Wintermar Pacific",
    companyId: "comp-4",
    companyName: "PT Wintermar Offshore Marine Tbk",
    issuingAuthority: "Kementerian Perhubungan RI",
    issueDate: "2022-05-12",
    expiryDate: "2026-08-01",
    daysRemaining: -9,
    status: "expired",
  },
  {
    id: "cert-107",
    certificateName: "ISPS International Ship Security Certificate",
    certificateNumber: "ISPS-2024-9981",
    category: "Safety & Security (ISM/ISPS)",
    vesselId: "vess-5",
    vesselName: "MT Samarinda Pioneer",
    companyId: "comp-5",
    companyName: "PT Samarinda Trans Energi",
    issuingAuthority: "DNV GL Maritime",
    issueDate: "2025-02-01",
    expiryDate: "2026-10-30",
    daysRemaining: 81,
    status: "near-expiry",
  },
];

const initialVessels: Vessel[] = [
  {
    id: "vess-1",
    name: "KM Samudera Sejahtera",
    imoNumber: "IMO 9821245",
    flag: "Indonesia (IDN)",
    vesselType: "Container Ship",
    companyId: "comp-1",
    companyName: "PT Samudera Indonesia Tbk",
    builtYear: 2018,
    grossTonnage: 18500,
    lengthOverallMeters: 172.5,
    seaworthinessStatus: "Tidak Layak Operasi",
    currentPortLocation: "Pelabuhan Tanjung Priok, Dermaga 201",
    certificates: [initialCertificates[0], initialCertificates[1]],
  },
  {
    id: "vess-2",
    name: "KM Temas Express",
    imoNumber: "IMO 9743321",
    flag: "Indonesia (IDN)",
    vesselType: "Container Ship",
    companyId: "comp-2",
    companyName: "PT Temas Tbk (Pelayaran Temas)",
    builtYear: 2016,
    grossTonnage: 24200,
    lengthOverallMeters: 198.0,
    seaworthinessStatus: "Layak Operasi",
    currentPortLocation: "Pelabuhan Tanjung Perak, Surabaya",
    certificates: [initialCertificates[2], initialCertificates[3]],
  },
  {
    id: "vess-3",
    name: "TB Trans Power 08 / BG Marine 302",
    imoNumber: "IMO 9611290",
    flag: "Indonesia (IDN)",
    vesselType: "Tugboat & Barge",
    companyId: "comp-3",
    companyName: "PT Trans Power Marine Tbk",
    builtYear: 2020,
    grossTonnage: 3800,
    lengthOverallMeters: 92.4,
    seaworthinessStatus: "Layak Operasi",
    currentPortLocation: "Pelabuhan Muara Jawa, Samarinda",
    certificates: [initialCertificates[4]],
  },
  {
    id: "vess-4",
    name: "AHTS Wintermar Pacific",
    imoNumber: "IMO 9528812",
    flag: "Indonesia (IDN)",
    vesselType: "Offshore Supply Vessel (OSV)",
    companyId: "comp-4",
    companyName: "PT Wintermar Offshore Marine Tbk",
    builtYear: 2019,
    grossTonnage: 4500,
    lengthOverallMeters: 78.0,
    seaworthinessStatus: "Dalam Perbaikan",
    currentPortLocation: "Galangan Shipyard Batam",
    certificates: [initialCertificates[5]],
  },
  {
    id: "vess-5",
    name: "MT Samarinda Pioneer",
    imoNumber: "IMO 9890012",
    flag: "Indonesia (IDN)",
    vesselType: "Oil Tanker",
    companyId: "comp-5",
    companyName: "PT Samarinda Trans Energi",
    builtYear: 2022,
    grossTonnage: 12800,
    lengthOverallMeters: 145.0,
    seaworthinessStatus: "Layak Operasi",
    currentPortLocation: "Dermaga Pertamina Balikpapan",
    certificates: [initialCertificates[6]],
  },
];

const initialVendors: Vendor[] = [
  {
    id: "vend-1",
    name: "PT Nusantara Marine Surveyors",
    expertise: "Marine Survey & Technical Inspection",
    operatingPorts: ["Tanjung Priok", "Tanjung Perak", "Batam", "Balikpapan"],
    rateCardSummary: "Rp 15.000.000 - Rp 35.000.000 per survey inspeksi",
    slaHours: 24,
    performanceRating: 4.8,
    completedTasksCount: 42,
    activeTasksCount: 3,
    contactName: "Budi Santoso, ST",
    contactEmail: "budi@nusantaramarine.co.id",
    contactPhone: "+62 811-9988-7766",
    status: "Mitra Aktif",
  },
  {
    id: "vend-2",
    name: "PT Divers Technical Subsea & Diving",
    expertise: "Underwater Hull & Tank Cleaning",
    operatingPorts: ["Tanjung Priok", "Merak", "Ciwandan", "Makassar"],
    rateCardSummary: "Rp 25.000.000 per hull cleaning + UWILD photo report",
    slaHours: 12,
    performanceRating: 4.9,
    completedTasksCount: 29,
    activeTasksCount: 2,
    contactName: "Capt. Irwan Ramli",
    contactEmail: "irwan@subseadiving.co.id",
    contactPhone: "+62 812-7766-5544",
    status: "Mitra Aktif",
  },
  {
    id: "vend-3",
    name: "PT Batam Fast Docking & Shiprepair",
    expertise: "Docking, Maintenance & Repair",
    operatingPorts: ["Batam", "Tanjung Balai Karimun"],
    rateCardSummary: "Berdasarkan rincian estimasi docking & sparepart",
    slaHours: 48,
    performanceRating: 4.5,
    completedTasksCount: 18,
    activeTasksCount: 1,
    contactName: "Tengku Zulkarnain",
    contactEmail: "tzulkarnain@batamfastdock.com",
    contactPhone: "+62 813-8899-0011",
    status: "Mitra Aktif",
  },
  {
    id: "vend-4",
    name: "PT Radio Navigasi Bahari Service",
    expertise: "Radio Communication & GMDSS Inspection",
    operatingPorts: ["Tanjung Priok", "Tanjung Perak", "Banjarmasin"],
    rateCardSummary: "Rp 8.500.000 per sertifikasi GMDSS & VDR Annual Test",
    slaHours: 24,
    performanceRating: 4.7,
    completedTasksCount: 51,
    activeTasksCount: 2,
    contactName: "Hendra Wijaya",
    contactEmail: "service@radionavigasi.co.id",
    contactPhone: "+62 815-4433-2211",
    status: "Mitra Aktif",
  },
  {
    id: "vend-5",
    name: "Klinik Utama Maritime Port Health",
    expertise: "Crew Medical Check & Certification",
    operatingPorts: ["Tanjung Priok", "Belawan", "Semarang"],
    rateCardSummary: "Rp 1.200.000 per kru kapal (MCU + Buku Kesehatan)",
    slaHours: 24,
    performanceRating: 4.6,
    completedTasksCount: 88,
    activeTasksCount: 4,
    contactName: "dr. Maya Anggraini",
    contactEmail: "mcu@maritimeporthealth.com",
    contactPhone: "+62 816-1122-3344",
    status: "Mitra Aktif",
  },
];

const initialLeads: LeadOpportunity[] = [
  {
    id: "lead-1",
    leadSource: "Inbound Website",
    companyName: "PT Pelayaran Meratus Line",
    businessType: "Container Carrier",
    contactName: "Irwan Setiawan",
    contactEmail: "irwan.s@meratusline.com",
    contactPhone: "+62 812-1111-2222",
    stage: "Lead",
    potentialValueMonthly: 280000000,
    priorityScore: 92,
    assignedSales: "Reza Rahadian (Sales Lead)",
    notes: "Tertarik layanan agen pengurusan sertifikat kapal peti kemas cepat.",
    lastActivityDate: "2026-08-08",
    createdAt: "2026-08-01",
  },
  {
    id: "lead-2",
    leadSource: "Referral Partner",
    companyName: "PT Offshore Energy Transport",
    businessType: "Offshore Support & Supply",
    contactName: "Capt. Donny Kusuma",
    contactEmail: "donny@offshoreenergy.co.id",
    contactPhone: "+62 811-3333-4444",
    stage: "Qualified",
    potentialValueMonthly: 195000000,
    priorityScore: 85,
    assignedSales: "Nadia Utami (Account Executive)",
    qualification: {
      vesselCountNeeded: 8,
      frequentlyExpiringCerts: ["ISM Code", "SIUPAL Extension", "OSV Safe Manning"],
      outsourcingNeeds: ["Underwater Hull Survey", "Crew Medical Checkup"],
      currentAgencyPainPoints: "Agen terdahulu sering terlambat mengurus izin clearance.",
      expectedStartDate: "2026-09-01",
      budgetRangeMonthly: "Rp 150.000.000 - Rp 220.000.000",
      decisionMakerName: "Direktur Operasional",
    },
    notes: "Membutuhkan SLA kepastian port clearance kurang dari 6 jam.",
    lastActivityDate: "2026-08-09",
    createdAt: "2026-07-25",
  },
  {
    id: "lead-3",
    leadSource: "Port Exhibition",
    companyName: "PT Kalimantan Coal Transporter",
    businessType: "Tug & Barge (Coal & Minerals)",
    contactName: "Agus Hermawan",
    contactEmail: "agus@kaltimcoaltrans.com",
    contactPhone: "+62 813-5555-6666",
    stage: "Discovery",
    potentialValueMonthly: 340000000,
    priorityScore: 96,
    assignedSales: "Reza Rahadian (Sales Lead)",
    qualification: {
      vesselCountNeeded: 25,
      frequentlyExpiringCerts: ["Class Load Line", "BKI Survey Certificate"],
      outsourcingNeeds: ["Outsource Technical Inspection", "Radio Comm Annual Test"],
      currentAgencyPainPoints: "Pengurusan sertifikat tongkang batubara lambat di KSOP Samarinda.",
      expectedStartDate: "2026-08-20",
      budgetRangeMonthly: "Rp 300.000.000 - Rp 400.000.000",
      decisionMakerName: "VP Supply Chain",
    },
    notes: "Sudah melakukan pertemuan discovery 1-on-1 dengan Tim Operasional.",
    lastActivityDate: "2026-08-07",
    createdAt: "2026-07-20",
  },
  {
    id: "lead-4",
    leadSource: "Outbound Sales",
    companyName: "PT Global Tanker Nusantara",
    businessType: "Oil & Chemical Tanker",
    contactName: "Kartika Putri",
    contactEmail: "kartika@globaltanker.co.id",
    contactPhone: "+62 818-7777-8888",
    stage: "Proposal Sent",
    potentialValueMonthly: 220000000,
    priorityScore: 88,
    assignedSales: "Nadia Utami (Account Executive)",
    notes: "Proposal versi v1.2 dikirim pada 6 Agustus 2026.",
    lastActivityDate: "2026-08-06",
    createdAt: "2026-07-15",
  },
  {
    id: "lead-5",
    leadSource: "Tender Portal",
    companyName: "PT Batam Bulk Logistics",
    businessType: "General Cargo & Breakbulk",
    contactName: "Fajar Nugraha",
    contactEmail: "fajar@batambulk.com",
    contactPhone: "+62 819-9999-0000",
    stage: "Negotiation",
    potentialValueMonthly: 160000000,
    priorityScore: 78,
    assignedSales: "Reza Rahadian (Sales Lead)",
    notes: "Finalisasi SLA tanggap darurat dan diskon bundling sertifikat.",
    lastActivityDate: "2026-08-10",
    createdAt: "2026-07-10",
  },
];

const initialProposals: Proposal[] = [
  {
    id: "prop-1",
    leadId: "lead-4",
    companyName: "PT Global Tanker Nusantara",
    version: "v1.2",
    sentDate: "2026-08-06",
    recipientPic: "Kartika Putri (Operations Manager)",
    status: "Sent",
    proposalValueMonthly: 220000000,
    validUntil: "2026-08-30",
    scopeSummary: "Keagenan kapal tanker & perpanjangan berkala sertifikat MARPOL/SOLAS.",
  },
  {
    id: "prop-2",
    leadId: "lead-5",
    companyName: "PT Batam Bulk Logistics",
    version: "v1.0",
    sentDate: "2026-07-28",
    recipientPic: "Fajar Nugraha (Logistics Director)",
    status: "Reviewed",
    proposalValueMonthly: 160000000,
    validUntil: "2026-08-25",
    scopeSummary: "Pengurusan sertifikat kapal kargo umum & emergency port agency.",
  },
];

const initialServiceRequests: ServiceRequest[] = [
  {
    id: "req-101",
    requestNo: "SR-2026-0801",
    title: "Perpanjangan Darurat Sertifikat SOLAS Safety Construction",
    companyId: "comp-1",
    companyName: "PT Samudera Indonesia Tbk",
    vesselId: "vess-1",
    vesselName: "KM Samudera Sejahtera",
    serviceType: "Certificate Renewal & Survey",
    stage: "In Progress",
    assigneeType: "internal",
    assigneeName: "Andi Wijaya (Ops Coordinator)",
    deadline: "2026-08-20",
    priority: "Urgent",
    progressPercentage: 65,
    description: "Sertifikat sisa 15 hari. Syahbandar Tanjung Priok telah dijadwalkan survey tanggal 14 Agus.",
    portLocation: "Pelabuhan Tanjung Priok",
    createdAt: "2026-08-02",
  },
  {
    id: "req-102",
    requestNo: "SR-2026-0802",
    title: "Outsource Survey Hull UWILD & Cleaning Tanki",
    companyId: "comp-1",
    companyName: "PT Samudera Indonesia Tbk",
    vesselId: "vess-1",
    vesselName: "KM Samudera Sejahtera",
    serviceType: "Outsource Technical Inspection",
    stage: "Assigned",
    assigneeType: "outsource",
    assigneeId: "vend-2",
    assigneeName: "PT Divers Technical Subsea & Diving",
    deadline: "2026-08-18",
    priority: "High",
    progressPercentage: 40,
    description: "Mitra diver subsea ditugaskan melakukan pembersihan lambung di bawah air.",
    portLocation: "Pelabuhan Tanjung Priok",
    createdAt: "2026-08-04",
  },
  {
    id: "req-103",
    requestNo: "SR-2026-0803",
    title: "Port Clearance & Formalities Keberangkatan Singapore",
    companyId: "comp-2",
    companyName: "PT Temas Tbk (Pelayaran Temas)",
    vesselId: "vess-2",
    vesselName: "KM Temas Express",
    serviceType: "Port Clearance & Formalities",
    stage: "Waiting Approval",
    assigneeType: "internal",
    assigneeName: "Siti Rahma (Staff Formalitas)",
    deadline: "2026-08-12",
    priority: "High",
    progressPercentage: 90,
    description: "Semua dokumen pas jalan dan port clearance selesai, menunggu TTE Syahbandar.",
    portLocation: "Pelabuhan Tanjung Perak",
    createdAt: "2026-08-06",
  },
  {
    id: "req-104",
    requestNo: "SR-2026-0804",
    title: "Inspeksi Radiotelefoni GMDSS Annual Test",
    companyId: "comp-3",
    companyName: "PT Trans Power Marine Tbk",
    vesselId: "vess-3",
    vesselName: "TB Trans Power 08 / BG Marine 302",
    serviceType: "Outsource Technical Inspection",
    stage: "Request Created",
    assigneeType: "outsource",
    assigneeId: "vend-4",
    assigneeName: "PT Radio Navigasi Bahari Service",
    deadline: "2026-08-25",
    priority: "Normal",
    progressPercentage: 10,
    description: "Request baru diajukan oleh Klien. Menunggu verifikasi berkas.",
    portLocation: "Pelabuhan Samarinda",
    createdAt: "2026-08-09",
  },
  {
    id: "req-105",
    requestNo: "SR-2026-0805",
    title: "Medical Checkup & Certification 12 ABK Kapal Tanker",
    companyId: "comp-5",
    companyName: "PT Samarinda Trans Energi",
    vesselId: "vess-5",
    vesselName: "MT Samarinda Pioneer",
    serviceType: "Certificate Renewal & Survey",
    stage: "Verified",
    assigneeType: "internal",
    assigneeName: "Rian Hidayat (HRD Ops)",
    deadline: "2026-08-28",
    priority: "Normal",
    progressPercentage: 25,
    description: "Verifikasi sertifikat pelaut & pemeriksaan kesehatan rutin.",
    portLocation: "Pelabuhan Balikpapan",
    createdAt: "2026-08-08",
  },
];

const initialOutsourceTasks: OutsourceTask[] = [
  {
    id: "out-201",
    serviceRequestId: "req-102",
    serviceRequestNo: "SR-2026-0802",
    title: "Underwater Hull Cleaning & Photo Inspection Report",
    vendorId: "vend-2",
    vendorName: "PT Divers Technical Subsea & Diving",
    expertise: "Underwater Hull & Tank Cleaning",
    stage: "In Progress",
    deadline: "2026-08-18",
    costActual: 25000000,
    notes: "Penyelam sudah di lokasi dermaga sejak pukul 08:00 WIB.",
  },
  {
    id: "out-202",
    serviceRequestId: "req-104",
    serviceRequestNo: "SR-2026-0804",
    title: "GMDSS Annual Radio Survey & VDR Calibration",
    vendorId: "vend-4",
    vendorName: "PT Radio Navigasi Bahari Service",
    expertise: "Radio Communication & GMDSS Inspection",
    stage: "Sent to Vendor",
    deadline: "2026-08-25",
    costActual: 8500000,
    notes: "Surat penunjukan mitra telah dikirim via email.",
  },
  {
    id: "out-203",
    serviceRequestId: "req-101",
    serviceRequestNo: "SR-2026-0801",
    title: "Independent Marine Hull Survey Report",
    vendorId: "vend-1",
    vendorName: "PT Nusantara Marine Surveyors",
    expertise: "Marine Survey & Technical Inspection",
    stage: "Submitted",
    deadline: "2026-08-14",
    submittedAt: "2026-08-10 11:30",
    deliverablesSummary: "Laporan hasil survey fisik lambung kapal & rekomendasi pengelasan.",
    costActual: 18000000,
    notes: "Laporan teknis siap untuk di-review tim operasional internal.",
  },
];

const initialRenewalReminders: RenewalReminder[] = [
  {
    id: "rem-1",
    certificateId: "cert-102",
    certificateName: "MARPOL Annex I Oil Pollution Prevention",
    vesselId: "vess-1",
    vesselName: "KM Samudera Sejahtera",
    companyId: "comp-1",
    companyName: "PT Samudera Indonesia Tbk",
    expiryDate: "2026-08-05",
    daysRemaining: -5,
    urgency: "Expired",
    reminderStatus: "Belum Dilihat",
    assignedPic: "Andi Wijaya",
  },
  {
    id: "rem-2",
    certificateId: "cert-106",
    certificateName: "Surat Izin Usaha Perusahaan Angkutan Laut (SIUPAL)",
    vesselId: "vess-4",
    vesselName: "AHTS Wintermar Pacific",
    companyId: "comp-4",
    companyName: "PT Wintermar Offshore Marine Tbk",
    expiryDate: "2026-08-01",
    daysRemaining: -9,
    urgency: "Expired",
    reminderStatus: "Dalam Diproses",
    assignedPic: "Bambang P.",
  },
  {
    id: "rem-3",
    certificateId: "cert-101",
    certificateName: "SOLAS Safety Construction Certificate",
    vesselId: "vess-1",
    vesselName: "KM Samudera Sejahtera",
    companyId: "comp-1",
    companyName: "PT Samudera Indonesia Tbk",
    expiryDate: "2026-08-25",
    daysRemaining: 15,
    urgency: "30-days",
    reminderStatus: "Dalam Diproses",
    assignedPic: "Andi Wijaya",
  },
  {
    id: "rem-4",
    certificateId: "cert-105",
    certificateName: "International Load Line Certificate",
    vesselId: "vess-3",
    vesselName: "TB Trans Power 08 / BG Marine 302",
    companyId: "comp-3",
    companyName: "PT Trans Power Marine Tbk",
    expiryDate: "2026-08-30",
    daysRemaining: 20,
    urgency: "30-days",
    reminderStatus: "Belum Dilihat",
    assignedPic: "Siti Rahma",
  },
  {
    id: "rem-5",
    certificateId: "cert-103",
    certificateName: "Document of Compliance (ISM Code)",
    vesselId: "vess-2",
    vesselName: "KM Temas Express",
    companyId: "comp-2",
    companyName: "PT Temas Tbk (Pelayaran Temas)",
    expiryDate: "2026-09-15",
    daysRemaining: 36,
    urgency: "60-days",
    reminderStatus: "Disetujui Syahbandar",
    assignedPic: "Rudi Hermawan",
  },
];

interface MaritimeStore {
  companies: Company[];
  vessels: Vessel[];
  certificates: Certificate[];
  vendors: Vendor[];
  leads: LeadOpportunity[];
  proposals: Proposal[];
  serviceRequests: ServiceRequest[];
  outsourceTasks: OutsourceTask[];
  renewalReminders: RenewalReminder[];

  // Mutations
  updateLeadStage: (id: string, stage: SalesStage) => void;
  addLead: (lead: Omit<LeadOpportunity, "id" | "createdAt" | "lastActivityDate">) => void;
  updateLeadQualification: (id: string, qualification: QualificationDiscoveryForm) => void;
  
  updateCompanyLifecycleStage: (id: string, stage: CompanyLifecycleStage) => void;
  
  updateServiceRequestStage: (id: string, stage: ServiceRequestStage) => void;
  assignServiceRequest: (id: string, assigneeType: "internal" | "outsource", assigneeName: string, assigneeId?: string) => void;
  addServiceRequest: (req: Omit<ServiceRequest, "id" | "requestNo" | "createdAt" | "progressPercentage" | "stage">) => void;

  updateOutsourceTaskStage: (id: string, stage: OutsourceTaskStage) => void;
  createOutsourceTask: (task: Omit<OutsourceTask, "id" | "stage">) => void;

  renewCertificate: (certId: string, newExpiryDate: string) => void;
}

export const useMaritimeStore = create<MaritimeStore>((set) => ({
  companies: initialCompanies,
  vessels: initialVessels,
  certificates: initialCertificates,
  vendors: initialVendors,
  leads: initialLeads,
  proposals: initialProposals,
  serviceRequests: initialServiceRequests,
  outsourceTasks: initialOutsourceTasks,
  renewalReminders: initialRenewalReminders,

  updateLeadStage: (id, stage) =>
    set((state) => ({
      leads: state.leads.map((lead) =>
        lead.id === id
          ? {
              ...lead,
              stage,
              lastActivityDate: new Date().toISOString().split("T")[0],
            }
          : lead
      ),
    })),

  addLead: (newLeadData) =>
    set((state) => {
      const newLead: LeadOpportunity = {
        ...newLeadData,
        id: `lead-${Date.now()}`,
        createdAt: new Date().toISOString().split("T")[0],
        lastActivityDate: new Date().toISOString().split("T")[0],
      };
      return { leads: [newLead, ...state.leads] };
    }),

  updateLeadQualification: (id, qualification) =>
    set((state) => ({
      leads: state.leads.map((lead) =>
        lead.id === id ? { ...lead, qualification, stage: "Qualified" as SalesStage } : lead
      ),
    })),

  updateCompanyLifecycleStage: (id, stage) =>
    set((state) => ({
      companies: state.companies.map((comp) =>
        comp.id === id ? { ...comp, lifecycleStage: stage } : comp
      ),
    })),

  updateServiceRequestStage: (id, stage) =>
    set((state) => ({
      serviceRequests: state.serviceRequests.map((req) => {
        if (req.id !== id) return req;
        let progressPercentage = req.progressPercentage;
        if (stage === "Request Created") progressPercentage = 10;
        if (stage === "Verified") progressPercentage = 25;
        if (stage === "Assigned") progressPercentage = 40;
        if (stage === "In Progress") progressPercentage = 65;
        if (stage === "Waiting Approval") progressPercentage = 90;
        if (stage === "Completed") progressPercentage = 100;
        if (stage === "Closed") progressPercentage = 100;
        return { ...req, stage, progressPercentage };
      }),
    })),

  assignServiceRequest: (id, assigneeType, assigneeName, assigneeId) =>
    set((state) => ({
      serviceRequests: state.serviceRequests.map((req) =>
        req.id === id
          ? {
              ...req,
              assigneeType,
              assigneeName,
              assigneeId,
              stage: "Assigned" as ServiceRequestStage,
              progressPercentage: 40,
            }
          : req
      ),
    })),

  addServiceRequest: (newReqData) =>
    set((state) => {
      const count = state.serviceRequests.length + 1;
      const newReq: ServiceRequest = {
        ...newReqData,
        id: `req-${Date.now()}`,
        requestNo: `SR-2026-080${count}`,
        stage: "Request Created",
        progressPercentage: 10,
        createdAt: new Date().toISOString().split("T")[0],
      };
      return { serviceRequests: [newReq, ...state.serviceRequests] };
    }),

  updateOutsourceTaskStage: (id, stage) =>
    set((state) => ({
      outsourceTasks: state.outsourceTasks.map((task) =>
        task.id === id ? { ...task, stage } : task
      ),
    })),

  createOutsourceTask: (taskData) =>
    set((state) => {
      const newTask: OutsourceTask = {
        ...taskData,
        id: `out-${Date.now()}`,
        stage: "Task Required",
      };
      return { outsourceTasks: [newTask, ...state.outsourceTasks] };
    }),

  renewCertificate: (certId, newExpiryDate) =>
    set((state) => ({
      certificates: state.certificates.map((cert) =>
        cert.id === certId
          ? {
              ...cert,
              expiryDate: newExpiryDate,
              daysRemaining: Math.ceil(
                (new Date(newExpiryDate).getTime() - new Date().getTime()) / (1000 * 3600 * 24)
              ),
              status: "valid",
            }
          : cert
      ),
      renewalReminders: state.renewalReminders.map((rem) =>
        rem.certificateId === certId
          ? { ...rem, reminderStatus: "Disetujui Syahbandar", daysRemaining: 365 }
          : rem
      ),
    })),
}));
